apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 3000