apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: react-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"