apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: example-app
data:
  nginx.conf: |
    events { }
    http {
      server {
        listen 80;
        server_name localhost;

        location /api {
          proxy_pass http://example-app-service:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
          proxy_pass http://frontend-app-service:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }